#!/usr/bin/env node
/**
 * Jira Service Management Cloud client for Aegis.
 *
 * The client is dry-run by default. Every persistent write requires both the
 * bare --execute flag and an exact, target-bound --confirm VALUE generated by
 * the immediately preceding preview/preflight. Credentials are read only after
 * a create/comment confirmation matches. Transition confirmations are derived
 * from live request state and the uniquely resolved transition, then recomputed
 * immediately before the POST to detect drift.
 *
 * Configuration (environment only):
 *   JIRA_SITE             bare <tenant>.atlassian.net hostname
 *   JIRA_EMAIL            API-token owner email
 *   JIRA_API_TOKEN        Atlassian API token
 *   JIRA_SERVICE_DESK_ID  optional default numeric service desk id
 *   JIRA_REQUEST_TYPE_ID  optional default numeric request type id
 *
 * Examples:
 *   node scripts/jira-client.js create --summary "..." --description "..."
 *   node scripts/jira-client.js comment --issue HELP-123 --body "..."
 *   node scripts/jira-client.js transition --issue HELP-123 --to Resolved --execute
 *
 * Exit codes: 0 success/preview; 1 input or confirmation refusal; 2 API/preflight
 * failure before a write; 3 a write was attempted and its resulting state is
 * unknown or could not be verified.
 */

'use strict';

const crypto = require('node:crypto');
const https = require('node:https');

const REQUEST_TIMEOUT_MS = 15000;
const TRANSITION_PAGE_LIMIT = 50;
const MAX_TRANSITION_PAGES = 100;
const EXIT_PARTIAL_UNKNOWN = 3;

const BOOLEAN_FLAGS = new Set(['execute', 'public']);
const VALUE_FLAGS = new Set([
  'service-desk',
  'request-type',
  'summary',
  'description',
  'on-behalf-of',
  'issue',
  'body',
  'to',
  'confirm',
]);
const KNOWN_FLAGS = new Set([...BOOLEAN_FLAGS, ...VALUE_FLAGS]);

class InputError extends Error {}
class ApiError extends Error {
  constructor(status = null) {
    super('Jira API request failed');
    this.status = Number.isInteger(status) ? status : null;
  }
}
class ContractError extends Error {}

const defaultOut = (message) => process.stdout.write(`${message}\n`);
const defaultErr = (message) => process.stderr.write(`${message}\n`);

function sha256Hex(value) {
  return crypto.createHash('sha256').update(value, 'utf8').digest('hex');
}

function serializePayload(payload) {
  return JSON.stringify(payload);
}

function normalizeSite(value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new InputError('JIRA_SITE is required and must be a bare <tenant>.atlassian.net hostname.');
  }
  if (value !== value.trim() || /[\x00-\x20\x7f]/.test(value)) {
    throw new InputError('JIRA_SITE must not contain whitespace or control characters.');
  }
  const normalized = value.toLowerCase();
  const match = normalized.match(/^([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)\.atlassian\.net$/);
  if (!match || match[1].length > 63) {
    throw new InputError('JIRA_SITE must be a bare <tenant>.atlassian.net hostname (no scheme, path, port, or trailing dot).');
  }
  return normalized;
}

function normalizePositiveId(value, label) {
  const text = value === undefined || value === null ? '' : String(value);
  if (!/^[1-9][0-9]*$/.test(text)) throw new InputError(`${label} must be a positive numeric id.`);
  return text;
}

function normalizeIssueKey(value) {
  if (typeof value !== 'string' || value !== value.trim() || /[\x00-\x20\x7f]/.test(value)) {
    throw new InputError('--issue must be one Jira issue key with no whitespace or control characters.');
  }
  const normalized = value.toUpperCase();
  if (!/^[A-Z][A-Z0-9_]{0,19}-[1-9][0-9]*$/.test(normalized)) {
    throw new InputError('--issue must be a Jira issue key such as HELP-123.');
  }
  return normalized;
}

function requireText(value, label, { controlsAllowed = true } = {}) {
  if (typeof value !== 'string' || value.trim().length === 0) throw new InputError(`${label} is required.`);
  if (value.includes('\0') || (!controlsAllowed && /[\x00-\x1f\x7f]/.test(value))) {
    throw new InputError(`${label} contains unsupported control characters.`);
  }
  return value;
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith('--')) {
      args._.push(token);
      continue;
    }
    if (token === '--' || token.startsWith('---')) throw new InputError(`Malformed flag: ${token}`);
    if (token.includes('=')) throw new InputError(`Flag values must be separate arguments; ${token} is not allowed.`);
    const key = token.slice(2);
    if (!KNOWN_FLAGS.has(key)) throw new InputError(`Unknown flag: --${key}`);
    if (Object.prototype.hasOwnProperty.call(args, key)) throw new InputError(`Duplicate flag: --${key}`);

    const next = argv[index + 1];
    if (BOOLEAN_FLAGS.has(key)) {
      if (next !== undefined && !next.startsWith('--')) {
        throw new InputError(`Boolean flag --${key} accepts no value.`);
      }
      args[key] = true;
      continue;
    }
    if (next === undefined || next.startsWith('--')) throw new InputError(`Flag --${key} requires a value.`);
    args[key] = next;
    index += 1;
  }
  return args;
}

function loadCredentials(env = process.env) {
  const missing = [];
  if (!env.JIRA_EMAIL) missing.push('JIRA_EMAIL');
  if (!env.JIRA_API_TOKEN) missing.push('JIRA_API_TOKEN');
  if (missing.length) throw new InputError(`Missing required env vars: ${missing.join(', ')}.`);
  return { email: String(env.JIRA_EMAIL), token: String(env.JIRA_API_TOKEN) };
}

function normalizeCredentials(credentials) {
  if (!credentials || typeof credentials.email !== 'string' || credentials.email.length === 0 ||
      typeof credentials.token !== 'string' || credentials.token.length === 0) {
    throw new InputError('Credential provider must return non-empty email and token values.');
  }
  return { email: credentials.email, token: credentials.token };
}

function buildCreatePayload({ serviceDeskId, requestTypeId, summary, description, raiseOnBehalfOf }) {
  const desk = normalizePositiveId(serviceDeskId, 'serviceDeskId');
  const type = normalizePositiveId(requestTypeId, 'requestTypeId');
  const safeSummary = requireText(summary, 'summary');
  const payload = {
    serviceDeskId: desk,
    requestTypeId: type,
    requestFieldValues: {
      summary: safeSummary,
      description: description === undefined ? '' : requireText(description, 'description'),
    },
  };
  if (raiseOnBehalfOf !== undefined) payload.raiseOnBehalfOf = requireText(raiseOnBehalfOf, 'on-behalf-of');
  return payload;
}

function buildCommentPayload({ body, isPublic }) {
  return { body: requireText(body, 'comment body'), public: isPublic === true };
}

function buildCreateConfirmation(site, payload) {
  const normalizedSite = normalizeSite(site);
  const digest = sha256Hex(serializePayload(payload));
  return `CREATE JSM REQUEST ON ${normalizedSite} DESK ${payload.serviceDeskId} TYPE ${payload.requestTypeId} PAYLOAD SHA256 ${digest}`;
}

function buildCommentConfirmation(site, issueKey, payload) {
  const normalizedSite = normalizeSite(site);
  const issue = normalizeIssueKey(issueKey);
  const visibility = payload.public === true ? 'PUBLIC' : 'INTERNAL';
  const digest = sha256Hex(serializePayload(payload));
  return `POST ${visibility} JSM COMMENT ON ${normalizedSite} ISSUE ${issue} PAYLOAD SHA256 ${digest}`;
}

function stateFingerprint(site, snapshot) {
  return sha256Hex(JSON.stringify({
    site: normalizeSite(site),
    issueKey: snapshot.issueKey,
    issueId: snapshot.issueId,
    currentStatus: snapshot.currentStatus,
    statusVersion: snapshot.statusVersion,
  }));
}

function transitionFingerprint(transition) {
  return sha256Hex(JSON.stringify({ id: transition.id, name: transition.name }));
}

function buildTransitionConfirmation(site, snapshot, transition) {
  const normalizedSite = normalizeSite(site);
  return `TRANSITION JSM ISSUE ${snapshot.issueKey} ID ${snapshot.issueId} ON ${normalizedSite} ` +
    `FROM STATE SHA256 ${stateFingerprint(normalizedSite, snapshot)} ` +
    `USING TRANSITION ${transition.id} SHA256 ${transitionFingerprint(transition)}`;
}

function isSuccessfulStatus(status) {
  return Number.isInteger(status) && status >= 200 && status < 300;
}

function apiRequest(cfg, method, apiPath, payload = null, options = {}) {
  if (typeof options === 'number') options = { timeoutMs: options };
  const timeoutMs = options.timeoutMs || REQUEST_TIMEOUT_MS;
  const requestImpl = options.request || https.request;
  const site = normalizeSite(cfg && cfg.site);
  const credentials = normalizeCredentials(cfg);
  const upperMethod = String(method).toUpperCase();
  if (!['GET', 'POST'].includes(upperMethod)) throw new InputError('Unsupported Jira API method.');
  if (typeof apiPath !== 'string' || !apiPath.startsWith('/rest/servicedeskapi/') ||
      /[\x00-\x20\x7f]/.test(apiPath) || apiPath.includes('://')) {
    throw new InputError('Jira API path must be a local /rest/servicedeskapi/ path without controls.');
  }
  if (!Number.isFinite(timeoutMs) || timeoutMs <= 0) throw new InputError('Request timeout must be positive.');

  return new Promise((resolve, reject) => {
    const data = payload === null || payload === undefined ? null : serializePayload(payload);
    const auth = Buffer.from(`${credentials.email}:${credentials.token}`, 'utf8').toString('base64');
    const requestOptions = {
      hostname: site,
      path: apiPath,
      method: upperMethod,
      headers: {
        Authorization: `Basic ${auth}`,
        Accept: 'application/json',
        ...(data === null ? {} : {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(data),
        }),
      },
    };

    let settled = false;
    let timer;
    const finishError = (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(error);
    };
    const request = requestImpl(requestOptions, (response) => {
      let raw = '';
      response.on('data', (chunk) => { raw += String(chunk); });
      response.on('error', finishError);
      response.on('end', () => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        let json = null;
        try { json = raw.length ? JSON.parse(raw) : null; } catch { /* response bodies are never echoed */ }
        resolve({ status: response.statusCode, body: raw, json });
      });
    });
    request.on('error', finishError);
    timer = setTimeout(() => {
      if (settled) return;
      const timeoutError = new Error(`Jira API request timed out after ${timeoutMs}ms`);
      request.destroy(timeoutError);
      finishError(timeoutError);
    }, timeoutMs);
    if (data !== null) request.write(data);
    request.end();
  });
}

function createRuntime(env, dependencies = {}) {
  return {
    env,
    fetch: dependencies.fetch || apiRequest,
    getCredentials: dependencies.getCredentials || loadCredentials,
    out: dependencies.out || defaultOut,
    err: dependencies.err || defaultErr,
  };
}

async function networkConfig(runtime, site) {
  const credentials = normalizeCredentials(await runtime.getCredentials(runtime.env));
  return { site: normalizeSite(site), ...credentials };
}

async function fetchResponse(runtime, cfg, method, apiPath, payload = null) {
  let response;
  try {
    response = await runtime.fetch(cfg, method, apiPath, payload);
  } catch {
    throw new ApiError();
  }
  if (!response || !Number.isInteger(response.status)) throw new ApiError();
  return response;
}

function requireSuccess(response) {
  if (!isSuccessfulStatus(response.status)) throw new ApiError(response.status);
  return response;
}

function reportConfirmationRefusal(runtime, expected) {
  runtime.err('Confirmation missing or mismatched. No write was attempted.');
  runtime.err(`Required confirmation: ${expected}`);
  return 1;
}

function reportPartialUnknown(runtime, action) {
  runtime.err(`${action} was attempted, but the resulting state is UNKNOWN/possibly changed.`);
  runtime.err('Inspect the exact Jira request before retrying; the client will not retry automatically.');
  return EXIT_PARTIAL_UNKNOWN;
}

function normalizeWriteReceipt(json, label) {
  if (!json || typeof json !== 'object') throw new ContractError(`Malformed ${label} receipt.`);
  let issueKey;
  try { issueKey = normalizeIssueKey(json.issueKey); }
  catch { throw new ContractError(`Malformed issue key in ${label} receipt.`); }
  const issueId = String(json.issueId === undefined ? '' : json.issueId);
  if (!/^[1-9][0-9]*$/.test(issueId)) throw new ContractError(`Invalid immutable issue id in ${label} receipt.`);
  return { issueKey, issueId };
}

function requireExactRequestField(json, fieldId, expectedValue) {
  if (!Array.isArray(json.requestFieldValues)) throw new ContractError('Request read-back has no field collection.');
  const matches = json.requestFieldValues.filter(field => field && field.fieldId === fieldId);
  if (matches.length !== 1 || typeof matches[0].value !== 'string' || matches[0].value !== expectedValue) {
    throw new ContractError(`Request read-back did not prove the exact ${fieldId} value.`);
  }
}

function verifyCreatedRequestReadBack(json, receipt, payload) {
  const observed = normalizeWriteReceipt(json, 'create read-back');
  if (observed.issueKey !== receipt.issueKey || observed.issueId !== receipt.issueId) {
    throw new ContractError('Create read-back identity did not match the POST receipt.');
  }
  let serviceDeskId;
  let requestTypeId;
  try {
    serviceDeskId = normalizePositiveId(json.serviceDeskId, 'read-back serviceDeskId');
    requestTypeId = normalizePositiveId(json.requestTypeId, 'read-back requestTypeId');
  } catch {
    throw new ContractError('Create read-back returned invalid request type identity.');
  }
  if (serviceDeskId !== payload.serviceDeskId || requestTypeId !== payload.requestTypeId) {
    throw new ContractError('Create read-back request type identity did not match the approved payload.');
  }
  requireExactRequestField(json, 'summary', payload.requestFieldValues.summary);
  requireExactRequestField(json, 'description', payload.requestFieldValues.description);
  return observed;
}

function normalizeCommentReceipt(json) {
  if (!json || typeof json !== 'object') throw new ContractError('Malformed comment receipt.');
  const id = String(json.id === undefined ? '' : json.id);
  if (!/^[1-9][0-9]*$/.test(id)) throw new ContractError('Comment receipt returned an invalid immutable id.');
  return { id };
}

function verifyCommentReadBack(json, receipt, payload) {
  if (!json || typeof json !== 'object') throw new ContractError('Malformed comment read-back.');
  const id = String(json.id === undefined ? '' : json.id);
  if (id !== receipt.id || typeof json.body !== 'string' || json.body !== payload.body || json.public !== payload.public) {
    throw new ContractError('Comment read-back did not prove the approved id, body, and visibility.');
  }
  return { id };
}

function normalizeCustomerRequest(json, expectedIssueKey) {
  if (!json || typeof json !== 'object') throw new ContractError('Malformed customer request response.');
  let issueKey;
  try { issueKey = normalizeIssueKey(json.issueKey); } catch { throw new ContractError('Malformed issue key in response.'); }
  if (issueKey !== expectedIssueKey) throw new ContractError('Jira returned a different issue key.');
  const issueId = String(json.issueId === undefined ? '' : json.issueId);
  if (!/^[1-9][0-9]*$/.test(issueId)) throw new ContractError('Jira returned an invalid immutable issue id.');
  const status = json.currentStatus && json.currentStatus.status;
  if (typeof status !== 'string' || status.length === 0 || /[\x00-\x1f\x7f]/.test(status)) {
    throw new ContractError('Jira returned an invalid current status.');
  }
  const date = json.currentStatus.statusDate || {};
  let statusVersion = '';
  if (Number.isInteger(date.epochMillis)) statusVersion = String(date.epochMillis);
  else if (typeof date.iso8601 === 'string' && !/[\x00-\x1f\x7f]/.test(date.iso8601)) statusVersion = date.iso8601;
  if (statusVersion.length === 0) throw new ContractError('Jira returned no valid current-status version.');
  return { issueKey, issueId, currentStatus: status, statusVersion };
}

function normalizeTransition(value) {
  if (!value || typeof value !== 'object') throw new ContractError('Malformed transition entry.');
  const id = String(value.id === undefined ? '' : value.id);
  if (!/^[0-9]+$/.test(id)) throw new ContractError('Transition id must be numeric.');
  const name = value.name;
  if (typeof name !== 'string' || name.trim().length === 0 || /[\x00-\x1f\x7f]/.test(name)) {
    throw new ContractError('Transition name is missing or contains control characters.');
  }
  return { id, name };
}

async function fetchAllTransitions(runtime, cfg, issueKey) {
  const transitions = [];
  const seenIds = new Set();
  let start = 0;

  for (let pageNumber = 0; pageNumber < MAX_TRANSITION_PAGES; pageNumber += 1) {
    const apiPath = `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}/transition` +
      `?start=${start}&limit=${TRANSITION_PAGE_LIMIT}`;
    const response = requireSuccess(await fetchResponse(runtime, cfg, 'GET', apiPath));
    const page = response.json;
    if (!page || typeof page !== 'object' || !Array.isArray(page.values) ||
        !Number.isInteger(page.start) || page.start !== start ||
        !Number.isInteger(page.size) || page.size !== page.values.length ||
        !Number.isInteger(page.limit) || page.limit <= 0 ||
        typeof page.isLastPage !== 'boolean') {
      throw new ContractError('Malformed or non-progressing Jira transition page.');
    }

    for (const raw of page.values) {
      const transition = normalizeTransition(raw);
      if (seenIds.has(transition.id)) throw new ContractError('Duplicate transition id returned across pages.');
      seenIds.add(transition.id);
      transitions.push(transition);
    }

    if (page.isLastPage) return transitions;
    const nextStart = start + page.values.length;
    if (nextStart <= start) throw new ContractError('Non-progressing Jira transition pagination.');
    start = nextStart;
  }
  throw new ContractError('Jira transition pagination exceeded the safety limit.');
}

function resolveTransition(transitions, selector) {
  const target = requireText(selector, 'to', { controlsAllowed: false });
  if (/^[0-9]+$/.test(target)) {
    const byId = transitions.filter((transition) => transition.id === target);
    if (byId.length !== 1) throw new ContractError(`Transition id ${target} did not resolve uniquely.`);
    return byId[0];
  }
  const folded = target.toLocaleLowerCase('en-US');
  const byName = transitions.filter((transition) => transition.name.toLocaleLowerCase('en-US') === folded);
  if (byName.length !== 1) throw new ContractError(`Transition name did not resolve uniquely (${byName.length} matches).`);
  return byName[0];
}

async function preflightTransition(runtime, cfg, issueKey, selector) {
  const requestPath = `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}`;
  const requestResponse = requireSuccess(await fetchResponse(runtime, cfg, 'GET', requestPath));
  const snapshot = normalizeCustomerRequest(requestResponse.json, issueKey);
  const transitions = await fetchAllTransitions(runtime, cfg, issueKey);
  const transition = resolveTransition(transitions, selector);
  const confirmation = buildTransitionConfirmation(cfg.site, snapshot, transition);
  return { snapshot, transition, confirmation };
}

async function cmdListDesks(runtime, args) {
  if (args.execute !== true) {
    runtime.out('DRY RUN - would GET /rest/servicedeskapi/servicedesk. Add --execute to perform this read.');
    return 0;
  }
  const site = normalizeSite(runtime.env.JIRA_SITE);
  const cfg = await networkConfig(runtime, site);
  const response = requireSuccess(await fetchResponse(runtime, cfg, 'GET', '/rest/servicedeskapi/servicedesk'));
  for (const desk of (response.json && response.json.values) || []) {
    runtime.out(`id=${String(desk.id)} key=${String(desk.projectKey)} name=${String(desk.projectName)}`);
  }
  return 0;
}

async function cmdListTypes(runtime, args) {
  const deskId = normalizePositiveId(args['service-desk'] || runtime.env.JIRA_SERVICE_DESK_ID, 'service desk id');
  const apiPath = `/rest/servicedeskapi/servicedesk/${encodeURIComponent(deskId)}/requesttype`;
  if (args.execute !== true) {
    runtime.out(`DRY RUN - would GET ${apiPath}. Add --execute to perform this read.`);
    return 0;
  }
  const site = normalizeSite(runtime.env.JIRA_SITE);
  const cfg = await networkConfig(runtime, site);
  const response = requireSuccess(await fetchResponse(runtime, cfg, 'GET', apiPath));
  for (const type of (response.json && response.json.values) || []) {
    runtime.out(`id=${String(type.id)} name=${String(type.name)}`);
  }
  return 0;
}

async function cmdCreate(runtime, args) {
  const site = normalizeSite(runtime.env.JIRA_SITE);
  const payload = buildCreatePayload({
    serviceDeskId: args['service-desk'] || runtime.env.JIRA_SERVICE_DESK_ID,
    requestTypeId: args['request-type'] || runtime.env.JIRA_REQUEST_TYPE_ID,
    summary: args.summary,
    description: args.description,
    raiseOnBehalfOf: args['on-behalf-of'],
  });
  const confirmation = buildCreateConfirmation(site, payload);
  runtime.out(`${args.execute === true ? 'EXECUTION CANDIDATE' : 'DRY RUN'} - exact POST payload: ${serializePayload(payload)}`);
  runtime.out(`Required confirmation: ${confirmation}`);
  if (args.execute !== true) return 0;
  if (args.confirm !== confirmation) return reportConfirmationRefusal(runtime, confirmation);

  const cfg = await networkConfig(runtime, site);
  let response;
  try { response = await fetchResponse(runtime, cfg, 'POST', '/rest/servicedeskapi/request', payload); }
  catch { return reportPartialUnknown(runtime, 'Create-request POST'); }
  if (response.status !== 201 || !response.json) return reportPartialUnknown(runtime, 'Create-request POST');
  let receipt;
  try { receipt = normalizeWriteReceipt(response.json, 'create'); }
  catch { return reportPartialUnknown(runtime, 'Create-request POST'); }
  try {
    const readBack = await fetchResponse(
      runtime,
      cfg,
      'GET',
      `/rest/servicedeskapi/request/${encodeURIComponent(receipt.issueKey)}`
    );
    if (readBack.status !== 200) throw new ContractError('Create read-back did not return HTTP 200.');
    verifyCreatedRequestReadBack(readBack.json, receipt, payload);
  } catch {
    return reportPartialUnknown(runtime, 'Create-request POST');
  }
  runtime.out(`Created request ${receipt.issueKey} ID ${receipt.issueId}; HTTP 201 receipt and independent GET read-back verified.`);
  return 0;
}

async function cmdComment(runtime, args) {
  const issueKey = normalizeIssueKey(args.issue);
  const site = normalizeSite(runtime.env.JIRA_SITE);
  const payload = buildCommentPayload({ body: args.body, isPublic: args.public });
  const confirmation = buildCommentConfirmation(site, issueKey, payload);
  const apiPath = `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}/comment`;
  runtime.out(`${args.execute === true ? 'EXECUTION CANDIDATE' : 'DRY RUN'} - exact POST payload: ${serializePayload(payload)}`);
  runtime.out(`Visibility: ${payload.public ? 'PUBLIC' : 'INTERNAL'}`);
  runtime.out(`Required confirmation: ${confirmation}`);
  if (args.execute !== true) return 0;
  if (args.confirm !== confirmation) return reportConfirmationRefusal(runtime, confirmation);

  const cfg = await networkConfig(runtime, site);
  let response;
  try { response = await fetchResponse(runtime, cfg, 'POST', apiPath, payload); }
  catch { return reportPartialUnknown(runtime, 'Comment POST'); }
  if (response.status !== 201 || !response.json) return reportPartialUnknown(runtime, 'Comment POST');
  let receipt;
  try { receipt = normalizeCommentReceipt(response.json); }
  catch { return reportPartialUnknown(runtime, 'Comment POST'); }
  try {
    const readBack = await fetchResponse(runtime, cfg, 'GET', `${apiPath}/${encodeURIComponent(receipt.id)}`);
    if (readBack.status !== 200) throw new ContractError('Comment read-back did not return HTTP 200.');
    verifyCommentReadBack(readBack.json, receipt, payload);
  } catch {
    return reportPartialUnknown(runtime, 'Comment POST');
  }
  runtime.out(`${payload.public ? 'PUBLIC' : 'INTERNAL'} comment ${receipt.id} on ${issueKey} verified by independent GET read-back.`);
  return 0;
}

async function cmdGet(runtime, args) {
  const issueKey = normalizeIssueKey(args.issue);
  const apiPath = `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}`;
  if (args.execute !== true) {
    runtime.out(`DRY RUN - would GET ${apiPath}. Add --execute to perform this read.`);
    return 0;
  }
  const site = normalizeSite(runtime.env.JIRA_SITE);
  const cfg = await networkConfig(runtime, site);
  const response = requireSuccess(await fetchResponse(runtime, cfg, 'GET', apiPath));
  const snapshot = normalizeCustomerRequest(response.json, issueKey);
  runtime.out(`${snapshot.issueKey} ID ${snapshot.issueId} status=${snapshot.currentStatus}`);
  return 0;
}

async function cmdTransition(runtime, args) {
  const issueKey = normalizeIssueKey(args.issue);
  const selector = requireText(args.to, 'to', { controlsAllowed: false });
  if (args.execute !== true) {
    runtime.out(`LOCAL PREVIEW - transition ${issueKey} using selector "${selector}".`);
    runtime.out('No API call was made. Add --execute for a read-only live preflight.');
    return 0;
  }

  const site = normalizeSite(runtime.env.JIRA_SITE);
  const cfg = await networkConfig(runtime, site);
  const first = await preflightTransition(runtime, cfg, issueKey, selector);
  runtime.out(`Preflight target: ${first.snapshot.issueKey} ID ${first.snapshot.issueId}; current status=${first.snapshot.currentStatus}.`);
  runtime.out(`Resolved transition: ID ${first.transition.id} name=${first.transition.name}.`);
  runtime.out(`Required confirmation: ${first.confirmation}`);

  if (args.confirm === undefined) {
    runtime.out('Read-only preflight complete. Re-run with --execute --confirm followed by the exact quoted phrase.');
    return 0;
  }
  if (args.confirm !== first.confirmation) return reportConfirmationRefusal(runtime, first.confirmation);

  const second = await preflightTransition(runtime, cfg, issueKey, selector);
  if (second.confirmation !== first.confirmation) {
    runtime.err('Preflight drift detected in request state or transition identity. No transition was posted.');
    runtime.err(`New required confirmation: ${second.confirmation}`);
    return 2;
  }

  const transitionPath = `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}/transition`;
  let postResponse;
  try { postResponse = await fetchResponse(runtime, cfg, 'POST', transitionPath, { id: second.transition.id }); }
  catch { return reportPartialUnknown(runtime, 'Transition POST'); }
  if (postResponse.status !== 204) return reportPartialUnknown(runtime, 'Transition POST');

  let readBackResponse;
  try {
    readBackResponse = requireSuccess(await fetchResponse(
      runtime,
      cfg,
      'GET',
      `/rest/servicedeskapi/request/${encodeURIComponent(issueKey)}`
    ));
  } catch {
    return reportPartialUnknown(runtime, 'Transition POST');
  }

  let after;
  try { after = normalizeCustomerRequest(readBackResponse.json, issueKey); }
  catch { return reportPartialUnknown(runtime, 'Transition POST'); }
  if (after.issueId !== second.snapshot.issueId || after.currentStatus === second.snapshot.currentStatus) {
    return reportPartialUnknown(runtime, 'Transition POST');
  }
  runtime.out(`Transition verified for ${after.issueKey} ID ${after.issueId}: ${second.snapshot.currentStatus} -> ${after.currentStatus}.`);
  return 0;
}

const COMMANDS = {
  'list-desks': cmdListDesks,
  'list-types': cmdListTypes,
  create: cmdCreate,
  comment: cmdComment,
  get: cmdGet,
  transition: cmdTransition,
};

async function run(argv = process.argv.slice(2), env = process.env, dependencies = {}) {
  const runtime = createRuntime(env, dependencies);
  let args;
  try {
    args = parseArgs(argv);
    const command = args._[0];
    if (!command || !COMMANDS[command] || args._.length !== 1) {
      throw new InputError('Usage: node scripts/jira-client.js <list-desks|list-types|create|comment|get|transition> [flags]');
    }
    return await COMMANDS[command](runtime, args);
  } catch (error) {
    if (error instanceof InputError) {
      runtime.err(`Input error: ${error.message}`);
      return 1;
    }
    if (error instanceof ApiError) {
      const suffix = error.status === null ? '' : ` (HTTP ${error.status})`;
      runtime.err(`Jira API request failed${suffix}; response body withheld.`);
      return 2;
    }
    if (error instanceof ContractError) {
      runtime.err(`Jira preflight/read-back contract failed: ${error.message} No write was attempted.`);
      return 2;
    }
    runtime.err('Jira operation failed safely; details withheld.');
    return 2;
  }
}

if (require.main === module) {
  run().then((code) => { process.exitCode = code; });
}

module.exports = {
  REQUEST_TIMEOUT_MS,
  TRANSITION_PAGE_LIMIT,
  EXIT_PARTIAL_UNKNOWN,
  apiRequest,
  buildCommentConfirmation,
  buildCommentPayload,
  buildCreateConfirmation,
  buildCreatePayload,
  buildTransitionConfirmation,
  fetchAllTransitions,
  loadCredentials,
  normalizeIssueKey,
  normalizeSite,
  normalizeWriteReceipt,
  parseArgs,
  preflightTransition,
  resolveTransition,
  run,
  serializePayload,
  sha256Hex,
  stateFingerprint,
  transitionFingerprint,
  verifyCommentReadBack,
  verifyCreatedRequestReadBack,
};
